import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        <Navbar />
        {children}
        <div className="min-h-full w-screen">hgfh</div>
        <Footer />
      </body>
    </html>
  );
}
